version: '3.8'
 
services:
 my_sql:
   platform: linux/amd64
   image: mariadb:10.0.33 # Same as ConoHa DB Server
   container_name: a_plus_tsukuba-db
   environment:
     MYSQL_PORT: 3306
     MYSQL_ROOT_PASSWORD: rootpass
     MYSQL_DATABASE: vhoi5_aplus_tsukuba
     TZ: Asia/Tokyo  
   ports:
     - 3307:3306 # To avoid port conflict, use 3307.
   # 文字コード設定とsql_modeをconohaに合わせる 
   # ConoHa DBサーバーではデータベース権限しかもらえない
   # utf8mb4とsql_modeの設定は.env側（django側＝セッションスコープ変数）で行うことで権限不足を回避する
   command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --sql_mode=""
   volumes:
     - data-volume:/var/lib/mysql
   healthcheck:
        test: mysqladmin ping -h 127.0.0.1 -u root -p$$MYSQL_ROOT_PASSWORD
     
 web:
    build: .
    container_name: a_plus_tsukuba-web
    ports:
      - 8000:8000
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      my_sql:
        condition: service_healthy # wait db starting
    # プログラムフォルダをボリューム指定する
    ## .envファイルなどを考慮して、以下のフォルダのみを対象にする。
    volumes:
      - ./A_plus_Tsukuba:/a_plus_tsukuba/A_plus_Tsukuba
      - ./board:/a_plus_tsukuba/board
 
volumes:
 data-volume:
