name: Django CI

on: [push, pull_request]

jobs:
  test: #Poetry+.env+pytest.ini+Docker

    name: Run Test Code

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    # テストを実行
    - name: build
      run: |
        docker-compose up -d --build
    - name: create tables
      run: |
        docker ps
        docker-compose exec -T a_plus_tsukuba-web-1 python manage.py makemigrations board
        docker-compose exec -T a_plus_tsukuba-web-1 python manage.py migrate
    - name: Test
      run: |
        docker-compose exec -T a_plus_tsukuba-web-1 pytest


  
