name: Django CI

on: [push, pull_request]

jobs:
  test: #Poetry+.env+pytest.ini+Docker

    name: Run Test Code

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: generate .env
      run: |
        chmod +x set-up-env.test.sh && sh set-up-env.test.sh
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DEBUG: ${{ secrets.DEBUG }}
        ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        DJANGO_SETTINGS_MODULE: ${{ secrets.DJANGO_SETTINGS_MODULE }}
    # テストを実行
    - name: build
      run: |
        docker-compose up -d --build
    - name: Test
      run: |
        docker-compose exec -T a_plus_tsukuba-web-1 pytest


  
