name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test: #Poetry+.env+pytest.ini+Docker

    name: Run Test Code

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
        uses: actions/checkout@v2
    - name: generate .env
        # 権限を755に変えてset-up-env.test.shを実行します
        # 権限を変えないとpermisson deniedと怒られ、実行できなくなります
        run: chmod +x set-up-env.test.sh && sh set-up-env.test.sh
        # 後述のsecretsを設定します
        # secretsの環境変数の値をMYSQL_ROOT_PASSWORDなどの変数に代入します
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: ${{ secrets.DEBUG }}
          ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DJANGO_SETTINGS_MODULE: ${{ secrets.DJANGO_SETTINGS_MODULE }}
      # テストを実行
      - name: Test
        run: |
          docker-compose up -d --build
          docker-compose exec -T app poetry run pytest --cov=board/tests/


  
